### ISSUE TITLE
User can create an itinerary

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#1]
# Task List
- [x] Create a components folder within the client folder
- [x] create a createButton.jsx file in the components folder
- [x] In createButton.jsx:
- [x] import react from 'react'
- [x] export default and create a react component with the following:
- [x] a handleClick method, which sets state to isCreating: true
- [x] a render method for a button element with the text: Create New Itinerary + and the class "create button"
- [x] create a file in the components folder named header.jsx
- [x] in header.jsx: create and export a component that renders a header with the h1: Travel Planner and give it the class "header" 
- [x] in home.jsx:
- [x] import the header and createButton components
- [x] create a class that renders the homepage with the header and createButton components included, as well as a placeholder background map image
- [x] create a component called createForm.jsx and in createForm:
- [x] render a form element containing a text input (with the placeholder text New Itinerary) and a submit button
- [x] add handleChange and handleSubmit methods:
- [x]  - it should also set state.isCreating to false
- [x] create a file in pages called create.jsx and in create.jsx:
- [x] render the header.jsx component and the createForm.jsx component
- [x] in app.jsx:
- [x] import the home page class
- [x] create and export an app class that:
- [x] renders the homepage if isCreating is false
- [x] renders the create page if isCreating is true
- [x] import and render the app in index.js
- [x] build a database with schema: itineraries
- [x] add a post method to the app in index.js that:
- [x]  - inserts the itinerary into the itineraries table
- [x] add errorMiddleware file to server folder that declares an error function
- [x] add a fetch request with a POST method  to handleSubmit in createForm that inserts data into db
- [x] test table functionality by sending a get request using HTTPie
- [x] in styles.css, style the button to match the look and position seen in the wireframe
- [x] style the header to match the wireframe

# Screenshots 

![Screen Shot 2021-04-05 at 5 25 36 PM](https://user-images.githubusercontent.com/76799878/113642354-76c4b200-9634-11eb-94e6-61be6b0de0a5.png)
![Screen Shot 2021-04-05 at 5 27 54 PM](https://user-images.githubusercontent.com/76799878/113642308-61e81e80-9634-11eb-9b1a-74447c19bfea.png)
