### ISSUE TITLE
User can navigate app using nav-bar

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#13]
# Task List
- [x] Add two anchor tags to the header component that only appear if the screen is in desktop mode
- [x] each anchor tag ('Create', 'View Itineraries') should have a corresponding href attribute that changes the site's hash location
- [x] if the site is in mobile mode, a fixed navbar should appear at the bottom of the screen with the same anchor tags
- [x] add css to ensure site looks good and works properly in desktop mode
- [x] add a background image to home page
- [x] finalize css
- [x] fix any remaining errors

# Screenshots
![Screen Shot 2021-04-05 at 5 45 45 PM](https://user-images.githubusercontent.com/76799878/113643259-c4dab500-9636-11eb-8f13-069d9d5e9dea.png)
![Screen Shot 2021-04-05 at 5 46 01 PM](https://user-images.githubusercontent.com/76799878/113643263-c73d0f00-9636-11eb-9f35-0d08ad5b1365.png)
