### ISSUE TITLE
User can view itinerary

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#17]
# Task List
- [x] Add required prop to trip name form input
- [x] add page called itinerary
- [x] add component named viewTrip
- [x] in app.jsx:
- [x]  - add currentTripName: '' and currentLocations: [] to this.state
- [x]  - add a trip parameter to toggleCreate, de-structure tripName and locations from trip if it exists, insert tripName and locations into their corresponding state properties using setState, and set isCreating to null if isCreating is truthy
- [x]  - pass toggleCreate as a prop for the Create component, then within Create pass it as a prop for CreateForm
- [x]  - put this.state.currentLocations and this.state.currentTripName into an object and assign it to the const trip
- [x]  - pass the trip object as a prop for Itinerary, then again within Itinerary for ViewTrip
- [x] in the handleSubmit method of createForm:
- [x]  - create a const toggleCreate with the value this.props.toggleCreate
- [x]  - call toggleCreate and pass the trip variable as an argument
- [x] in viewTrip.jsx, create a render method that:
- [x]  - de-structures name and locations from this.props.trip
- [x]  - declares the const 'locationsList' which calls the map method of locations and returns a list item with the value of the location name
- [x]  - renders an h1 with the value of tripName
- [x]  - renders a ul with locationsList as its value
- [x] check functionality by creating a new itinerary
- [x] add link to font awesome icons to head of index.html
- [x] add placeholder numbers and icons for restaurants & points of interest to each list item in locationsList
- [x] style the itinerary page to match the wireframe
- [x] finalize css
- [x] fix any errors

# Screenshots
![Screen Shot 2021-04-12 at 11 44 10 AM](https://user-images.githubusercontent.com/76799878/114444983-5a6ccc00-9b84-11eb-9c5a-33c6516e714a.png)
