### ISSUE TITLE
User can view location page

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#19]
# Task List
- [x] In map.jsx:
- [x]  - replace the empty string in state.location with an object containing these properties: name, lat, lng, points of interest, restaurants
- [x]  - in .on(request), de-structure the lng and lat from the result and upsdate each setState method with the new location object
- [x] Add a component named ViewLocation to components directory
- [x] Within app.jsx:
- [x]  - add a view property with the value 'itinerary' and a locationView property with the value of an empty object to state
- [x]  - create a method called toggleView, which takes a location as an argument
- [x]  - in toggleView, set state.view to 'location' and state.location view to the location variable if it is currently equal to 'itinerary'
- [x]  - set state.view to 'itinerary' if it's currently equal to 'location'
- [x]  - Add conditionals to the renderPage method that render itinerary.jsx or locationPage.jsx for depending on state
- [x]  - pass toggleView to locationPage and itinerary, and again to the viewTrip and viewLocation components
- [x] Within ViewTrip:
- [x]  - add an onClick event to each list item that contains a callback function that calls the toggleView method with the location object as an argument
- [x]  - add a right-facing arrow to each list item
- [x] within ViewLocation, create a render method that returns:
- [x]  - a div with a back arrow icon and an h1 containing the location name
- [x]  - a ul with two list items: restaurants and points of interest
- [x]  - add an onClick event to the back arrow icon, which calls the toggleView method
- [x] check functionality by clicking on an itinerary location
- [x] add a component named locationMap to components
- [x] in locationMap:
- [x]  - take the coordinates found in this.props.location
- [x]  - create a centered on the lat and lng properties
- [x] in locationView:
- [x]  - insert the locationMap component into the render method in between the the name and restaurants/poi div
- [x]  - pass this.props.location as the prop location
- [x] style the page to match the wireframe
- [x] finalize css
- [x] fix any errors

# Screenshots
![Screen Shot 2021-04-13 at 10 45 03 AM](https://user-images.githubusercontent.com/76799878/114597155-4dfc7800-9c45-11eb-8ff4-0b596d57d200.png)
