### ISSUE TITLE
 User can search for locations & view them on an interactive map

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#2]
# Task List
- [x] install mapbox dependencies
- [ ] create and export a Map component that renders an interactive mapbox map
- [ ] in createForm.jsx, import the Map component and insert it into the render method
- [ ] style the map to match each wireframe
- [ ] add geocoder functionality to the Map component
- [ ] style searchbar to match the wireframe
- [ ] style the map's buttons to not overlap website form inputs
- [ ] finalize css
- [ ] fix any errors

# Screenshots
![Screen Shot 2021-04-05 at 5 32 09 PM](https://user-images.githubusercontent.com/76799878/113642522-e175ed80-9634-11eb-8b82-a437dc89c705.png)
![Screen Shot 2021-04-05 at 5 32 23 PM](https://user-images.githubusercontent.com/76799878/113642525-e2a71a80-9634-11eb-821d-b51836107a61.png)

**Comment by james-w-roach** [comment]
![Screen Shot 2021-04-05 at 5 26 03 PM](https://user-images.githubusercontent.com/76799878/113642410-9bb92500-9634-11eb-855f-73f8e30a9199.png)
