### ISSUE TITLE
User can search for locations & view them on an interactive map

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#3]
# Task List
- [x] install mapbox dependencies
- [x] create and export a Map component that renders an interactive mapbox map
- [x] in createForm.jsx, import the Map component and insert it into the render method
- [x] style the map to match each wireframe
- [x] add geocoder functionality to the Map component
- [x] style searchbar to match the wireframe
- [x] style the map's buttons to not overlap website form inputs
- [x] finalize css
- [x] fix any errors

# Screenshots
![Screen Shot 2021-04-05 at 5 33 43 PM](https://user-images.githubusercontent.com/76799878/113642630-1b46f400-9635-11eb-863a-e48ec4a90850.png)
![Screen Shot 2021-04-05 at 5 34 07 PM](https://user-images.githubusercontent.com/76799878/113642636-1e41e480-9635-11eb-8e85-2bf169e19dbb.png)
