### ISSUE TITLE
 User can add locations to their itinerary

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#4]
# Task List
- [x] Update schema.sql to allow for a "locations" column
- [x] update the app.post method in index.js:
- [x]  - add the locations property to the destructuring of req.body
- [x]  - for the sql const, add the "locations" column to the insert and returning lines and add $2 to values
- [x]  - add the locations const to the params array
- [x] In the state object of createForm.jsx, add a locations property with the value of an empty array
- [x] in map.jsx:
- [x]  - add a form to the render method that includes a submit input and that calls the method "handleAdd" onSubmit
- [x]  - add and bind the "handleAdd" method
- [x]  - handleAdd should call event.preventDefault(), create an const newLocation which is an object that includes the lng, lat, and location properties of this.state, and passes newLocation into this.props.onSubmit()
- [x]  - for the value of the submit input, insert a template literal that says 'Add' and then returns the text before the first comma in this.state.location using the split method
- [x] in createForm.jsx:
- [x]  - add and bind a "handlePush" method, which pushes the newLocation object from handleAdd into this.state.locations
- [x]  - in the render method, add an onSubmit prop to <Mapbox /> with the value this.handlePush
- [x] test functionality by adding locations, submitting the trip, and checking the database to see if they appear
- [x] add a method to map.jsx called setAddClass that checks if the location name already exists in local storage & changes the class of the add button
- [x] also add a setAddValue that checks local storage & changes the value of the add button depending on if location has been added to localStorage
- [x] add code to the handleAdd method that:
- [x]  - converts the location name to JSON and stores it in localstorage if it's not already there
- [x] add an 'inLocalStorage' property to this.state and set it to null
- [x] add code to the on method of map.addControl that:
- [x]  - parses 'locations' item from localStorage if it exists
- [x]  - sets the truthiness of this.state.inLocalStorage depending on if the result is in localStorage
- [x]  - sets this.state.location to locationName
- [x] in handleAdd:
- [x]  -  only lift the newLocation prop if the location is not in localStorage
- [x]  - if it is in local storage, create a window alert that notifies the user of this
- [x]  - call this.setAddClass in both condition blocks
- [ ] add a method that hides the add button and shows the finish button after 2 seconds  
- [ ] style the add button to match the wireframe
- [ ] finalize css
- [ ] fix any errors

# Screenshots
![Screen Shot 2021-04-05 at 5 26 09 PM](https://user-images.githubusercontent.com/76799878/113642710-521d0a00-9635-11eb-95d1-f149a60b13a5.png)
![Screen Shot 2021-04-05 at 5 36 21 PM](https://user-images.githubusercontent.com/76799878/113642753-6bbe5180-9635-11eb-91b5-31479c5ab762.png)
