### ISSUE TITLE
User can view location specific restaurants

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#6]
#Task List
- [ ] Add a file to pages called restaurants
- [ ] 
- [ ] in restaurants:
- [ ]  - create and export the restaurants class
- [ ]  - insert the header, viewRestaurants, and a placeholder 'Add to this list +' button
- [ ] Render the restaurant page using hash routing

#Screenshots
![Screen Shot 2021-04-05 at 5 28 42 PM](https://user-images.githubusercontent.com/76799878/113642859-a6c08500-9635-11eb-9a0b-8b54c70d6b5f.png)
![Screen Shot 2021-04-05 at 5 26 38 PM](https://user-images.githubusercontent.com/76799878/113642869-ab853900-9635-11eb-9ec0-605515bc3db0.png)
