### ISSUE TITLE
User can add location-specific points of interest to their itinerary

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#7]
# Task List
- [x] Add a page called addPOI
- [x] within addPOI:
- [x]  - create and export AddPOI component
- [x]  - add a search method
- [x]  - render a form input type submit
- [x]  - onSubmit, call the search method, which sends a get request to the Foursquare API
- [x]  - map through the results and render each one as a list item
- [x]  - add an 'Add' button to each list item, which pushes that item into an array in state
- [x]  - add a 'Save' button to the bottom of the page that sends a fetch request with method PUT to the database, replacing the database array with the array in state
- [x] - 'save' button should also send the user back to the location page
- [x] in viewLocation:
- [x]  - add a fetch request that gets the points of interest array for that specific location on ComponentDidMount
- [x]  - map through the array and list out each POI using the ViewPOI component
- [x] Add foursquare attribution images to AddPOI and ViewPOI
- [x] Add links to corresponding foursquare page in AddPOI and ViewPOI 

# Screenshots
![Screen Shot 2021-04-05 at 5 28 19 PM](https://user-images.githubusercontent.com/76799878/113642901-c0fa6300-9635-11eb-8d86-3437aec5e249.png)
![Screen Shot 2021-04-05 at 5 26 44 PM](https://user-images.githubusercontent.com/76799878/113642907-c5bf1700-9635-11eb-8b49-9807143a75fa.png)

**Comment by james-w-roach** [comment]
![Screen Shot 2021-04-05 at 5 28 19 PM](https://user-images.githubusercontent.com/76799878/113642901-c0fa6300-9635-11eb-8d86-3437aec5e249.png)
![Screen Shot 2021-04-05 at 5 26 44 PM](https://user-images.githubusercontent.com/76799878/113642907-c5bf1700-9635-11eb-8b49-9807143a75fa.png)
