### ISSUE TITLE
 User can view location specific points of interest

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#8]
# Task List
- [x] add a component named viewPOI to components
- [x] in viewPOI:
- [x]  - create and export the class ViewPOI
- [x]  - for now, have it render some placeholder list items with a name, photo, rating, and address
- [x] Import and insert ViewPOI into the ViewLocation component underneath the POI header
- [x] Ensure ViewPOI only takes up a certain amount of space and the list can be scrolled through within that space (page maintains it's original size)
- [x] Add a button to the bottom of the page with the textContent: "Add to this list +"
- [x] Style the page to match the wireframe
- [x] finalize css
- [x] fix any errors

# Screenshots
![Screen Shot 2021-04-17 at 1 25 40 PM](https://user-images.githubusercontent.com/76799878/115126030-0c3f3a80-9f81-11eb-8275-925f03404619.png)
