### ISSUE TITLE
User can view list of upcoming trips

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/final-project#9]
# Task List
- [x] Add a page named itineraryList to pages
- [x] reformat code to implement hash routing
- [x] Add a back button to viewTrip that renders the itineraryList page when clicked
- [x] in itineraryList,
- [x]  - submit a fetch request that gets all available itineraries from the database
- [x]  - map through the array of itineraries and render each one
- [x]  - each rendered trip should contain the tripName, the number of locations added to that trip, and a right arrow icon
- [x]  - each trip should have an onClick prop that opens the itinerary page for that trip
- [x]  - if the fetch request response is empty, the page should render a message that says "no trips added yet"
- [x] test functionality
- [x] style itinerary page to match wireframe
- [x] finalize css
- [x] fix any errors

# Screenshots
![Screen Shot 2021-04-05 at 5 28 05 PM](https://user-images.githubusercontent.com/76799878/113643033-1f274600-9636-11eb-87c3-feca178c3bf1.png)
![Screen Shot 2021-04-05 at 5 42 10 PM](https://user-images.githubusercontent.com/76799878/113643070-3a925100-9636-11eb-94dd-18489500b088.png)
